services:
  - type: web
    name: ApiRaul
    env: python
    buildCommand: ""
    startCommand: |
      python manage.py migrate && gunicorn DjangoProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoProject.settings
