services:
  - type: web
    name: ApiRaul
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput
      gunicorn DjangoProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoProject.settings
      - key: PYTHON_VERSION
        value: 3.11
