# Generated by Django 5.1.7 on 2025-04-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='DiaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagenUrl', models.URLField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.rutina')),
            ],
        ),
    ]
