# Generated by Django 5.1.7 on 2025-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dieta_options_alter_rutina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagenUrl', models.URLField()),
            ],
            options={
                'db_table': 'dias_dieta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='diaentrenamiento',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='dieta',
            table='dietas',
        ),
        migrations.AlterModelTable(
            name='rutina',
            table='rutinas',
        ),
    ]
