# Generated by Django 5.1.7 on 2025-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diadieta_alter_diaentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('repeticiones', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejercicios_dia',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='diaentrenamiento',
            table='dias_entrenamiento',
        ),
    ]
