# Generated by Django 5.1.7 on 2025-04-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ejerciciodia_alter_diaentrenamiento_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dia_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='core.diadieta')),
            ],
            options={
                'db_table': 'comidas_dia',
            },
        ),
    ]
