# Generated by Django 5.1.7 on 2025-04-13 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comidadia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritmoCardiaco', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('logros', models.IntegerField()),
                ('disciplina', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('resistencia', models.IntegerField()),
            ],
            options={
                'db_table': 'estadisticas_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.IntegerField()),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comidadia',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
